version: '3.7'

services:
  eventbus_service:
    volumes:
      - ./eventbus-service/src:/app/src
    command: yarn dev:server

  post_service:
    volumes:
      - ./post-service/src:/app/src
    command: yarn dev:server

  comment_service:
    volumes:
      - ./comment-service/src:/app/src
    command: yarn dev:server

  webclient_service:
    build:
      context: ./webclient-service
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./webclient-service/src:/app/src
      - ./webclient-service/public:/app/public

  post_service_me:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=post_service_db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345678
    networks:
      - post_service_network

  comment_service_me:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=comment_service_db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345678
    networks:
      - comment_service_network
