version: '3.7'

services:
  post_service:
    build: ./post-service
    environment:
      - MONGO_CONNECTION_URI=mongodb://root:12345678@post_service_db/posts?authSource=admin
    ports:
      - 3001:3000
    volumes:
      - ./post-service/src:/app/src
    networks:
      - post_service_network
    depends_on:
      - post_service_db

  post_service_db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    networks:
      - post_service_network

  comment_service:
    build: ./comment-service
    environment:
      - MONGO_CONNECTION_URI=mongodb://root:12345678@comment_service_db/posts?authSource=admin
    ports:
      - 3002:3000
    volumes:
      - ./comment-service/src:/app/src
    networks:
      - comment_service_network
    depends_on:
      - comment_service_db

  comment_service_db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    networks:
      - comment_service_network

  webclient_service:
    build: ./webclient-service
    environment:
      - REACT_APP_POST_SERVICE_BASE_URL=http://localhost:3001/api/posts
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./webclient-service/src:/app/src
      - ./webclient-service/public:/app/public

networks:
    post_service_network:
      driver: bridge

    comment_service_network:
      driver: bridge

