version: '3.7'

services:
  post_service:
    volumes:
      - ./post-service/src:/app/src
    command: yarn dev:server

  comment_service:
    volumes:
      - ./comment-service/src:/app/src
    command: yarn dev:server

  webclient_service:
    build:
      context: ./webclient-service
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./webclient-service/src:/app/src
      - ./webclient-service/public:/app/public
