version: '3.7'

services:
  post_service:
    build: ./post-service
    ports:
      - 3001:3000
    volumes:
      - ./post-service/src:/app/src

  comment_service:
    build: ./comment-service
    ports:
      - 3002:3000
    volumes:
      - ./comment-service/src:/app/src

